django/Website/Website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^challenge/', include('challenge.urls')),
    url(r'^admin/', admin.site.urls)
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/Website/challenge/urls.py
from django.conf.urls import url
from . import views

app_name = 'challenge'
urlpatterns = [
	# url(r'^$', views.UserView.as_view(), name='index'),
	url(r'^$', views.challenges_home, name='home'),
	url(r'^(?P<challenge_id>[0-9]+)/$', views.challenge_page, name='challenge'),
	url(r'^(?P<challenge_id>[0-9]+)/helpcomment/$', views.help_comment, name='base_help_comment'),
	url(r'^(?P<challenge_id>[0-9]+)/helpcomment/(((?P<comment_id>[0-9]+)/)*)$', views.help_comment, name='help_comment'),
	url(r'^(?P<challenge_id>[0-9]+)/submit/$', views.submit, name='submit'),
	url(r'^submit/$', views.process_submit, name='process_submit'),
	url(r'^helpcomment/(?P<comment_id>[0-9]+)/$', views.index_help_comment, name="comment"),
	url(r'^post_comment/$', views.process_help_comment, name='process_help_comment'),
	# url(r'^test(?P<challenge_id>[0-9]+)/$', views.test, name='test')
]

django/Website/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^about/$', views.about, name='about'),
]

django/Website/user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
	url(r'^user_index/$', views.user_index, name='all_users'),
	url(r'^(?P<user_id>[0-9]+)/$', views.user, name='user'),
	url(r'^login/$', views.login, name='login'),
	url(r'^li/$', views.process_login, name='process_login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^create_user/$', views.create_user, name='create_user'),
	url(r'^cu/$', views.process_new_user, name='process_new_user'),
	url(r'^changepicture(?P<user_id>[0-9]+)/$', views.change_user_picture, name='change_user_picture'),
	url(r'^cp(?P<user_id>[0-9]+)/$', views.process_change_user_picture, name='process_change_user_picture'),
	url(r'^group(?P<group_id>[0-9]+)/$', views.group, name='group'),
	url(r'^groups/$', views.group_index, name='group_index'),
	url(r'^create_group/$', views.create_group, name='create_group'),
	url(r'^cg/$', views.process_new_group, name='process_new_group'),
	url(r'^join_group(?P<group_id>[0-9]+)/$', views.join_group, name='join_group'),
	url(r'^leave_group(?P<group_id>[0-9]+)/$', views.leave_group, name='leave_group'),
]

django/Website/user/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage as FSS

class Group(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class User(models.Model):
	name = models.CharField(max_length=100)
	password = models.CharField(max_length=100, default="")
	email = models.EmailField(max_length=100)
	grad_year = models.IntegerField(default=0)
	groups = models.ManyToManyField(Group)
	user_picture = models.ImageField(upload_to="users\\", max_length=300, default='\\users\\default.jpg')

	def __str__(self):
		return self.name

django/Website/user/forms.py
from django import forms

class CreateUserForm(forms.Form):
	name = forms.CharField(label='name', max_length=100)
	email = forms.EmailField(label='email')
	grad_year = forms.IntegerField(label='grad_year')
	user_picture = forms.ImageField(label='user_picture', required=False)
	pwd = forms.CharField(label='pwd', max_length=100)
	pwd_check = forms.CharField(label='pwd_check', max_length=100)

class LoginForm(forms.Form):
	email = forms.CharField(label='email', max_length=100)
	pwd = forms.CharField(label='pwd', max_length=100)

class ChangePictureForm(forms.Form):
	user_picture = forms.ImageField(label='user_picture')

class CreateGroupForm(forms.Form):
	group_name = forms.CharField(label='group_name', max_length=100)
	

django/Website/user/views.py
from django.shortcuts import get_object_or_404, render
from Website.python import tools
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import User, Group
from challenge.models import Submission
from home.models import Picture
from .forms import CreateUserForm, LoginForm, CreateGroupForm

class UserView(generic.DetailView):
	model = User
	template_name = 'user/user.html'

def user(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	current_user = tools.validate_current_user(request.session, user.id)
	submissions = []
	for group in user.groups.all():
		for submission in Submission.objects.filter(group=group):
			if submission:
				submissions.append(submission)

	return render(request, 'user/user.html', {
		'user': user,
		'current_user': current_user,
		'submissions': submissions,
		})

def login(request):
	return render(request, 'user/login.html', {})

def logout(request):
	try:
		del request.session['user_id']
	except KeyError:
		pass

	return HttpResponseRedirect('/')

def process_login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			user = User.objects.get(email=request.POST['email'])
			if user.password == request.POST['pwd']:
				request.session['user_id'] = user.id
				return HttpResponseRedirect('/user/' + str(user.id) + '/')
			else:
				return HttpResponseRedirect('/user/login/')
		else:
			return HttpResponse("Form is not valid")

def process_new_user(request):
	if request.method == 'POST':
		form = CreateUserForm(request.POST, request.FILES)
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			grad_year = form.cleaned_data['grad_year']
			user_picture = form.cleaned_data['user_picture']
			pwd = form.cleaned_data['pwd']
			pwd_check = form.cleaned_data['pwd']

			if not pwd == pwd_check:
				raise ValidationError(_("Passwords don't match"), code='invalid')

			if not tools.verify_email(email):
				return HttpResponse("Invalid email")

			individual_group = Group(name=email.split("@")[0])
			individual_group.save()

			# If the user uploaded a profile picture
			if user_picture:
				user = User(name=name, email=email, grad_year=grad_year, password=pwd, user_picture=user_picture)
			else:
				user = User(name=name, email=email, grad_year=grad_year, password=pwd)

			user.save()
			user.groups.add(individual_group)
			request.session['user_id'] = user.id

			return HttpResponseRedirect('/user/' + str(user.id) + '/')
			
		else:
			return HttpResponse("Form is not valid")

	return render(request, 'user/create_user.html', {})

def create_user(request):
	return render(request, 'user/create_user.html', {})

def user_index(request):
	all_users = User.objects.order_by("name")
	return render(request, 'user/user_index.html', {
			'all_users': all_users,
		})

def change_user_picture(request, user_id):
	return render(request, 'user/change_user_picture.html', {
		'user_id': user_id,
		})

def process_change_user_picture(request, user_id):
	if (tools.validate_current_user(request, user_id)):
		if request.method == 'POST':
			form = ChangePictureForm(request.POST, request.FILES)
			if form.is_valid():
				user = get_object_or_404(User, pk=user_id)
				user_picture = form.cleaned_data['user_picture']
				user.user_picture = user_picture
				user.save()
				return HttpResponseRedirect('/user/' + str(user.id) + '/')
			else:
				return HttpResponse("Form is not valid")
		else:
			return HttpResponseRedirect('/user/' + str(user_id) + '/')
	else:
		return HttpResponse("Invalid credentials id=" + str(user_id) + ' when id should equal: ' + str(request.session['user_id']))

def group(request, group_id):
	group = get_object_or_404(Group, pk=group_id)
	group_members = User.objects.filter(groups=group)
	user = User.objects.get(pk=request.session['user_id'])
	user_in_group = (user in group_members)
	return render(request, 'user/group.html', {
			'group': group,
			'group_members': group_members,
			'user_in_group': user_in_group,
		})

def group_index(request):
	groups = Group.objects.all
	return render(request, 'user/group_index.html', {
			'groups': groups,
		})

def create_group(request):
	return render(request, 'user/create_group.html', {})

def process_new_group(request):
	if request.method == 'POST':
		form = CreateGroupForm(request.POST)
		if form.is_valid():
			name = form.cleaned_data['group_name']
			user = User.objects.get(pk=request.session['user_id'])
			new_group = Group(name=name)
			new_group.save()
			user.groups.add(new_group)
			user.save()

			return HttpResponseRedirect('/user/group' + str(new_group.id) + '/')
		else:
			return HttpResponse("Form is invalid")
	else:
		return HttpResponseRedirect('/user/create_group/')

def join_group(request, group_id):
	user = User.objects.get(pk=request.session['user_id'])
	group = Group.objects.get(pk=group_id)
	user.groups.add(group)
	user.save()

	return HttpResponseRedirect('/user/group' + str(group_id) + '/')

def leave_group(request, group_id):
	user = User.objects.get(pk=request.session['user_id'])
	group = Group.objects.get(pk=group_id)
	user.groups.remove(group)
	user.save()

	return HttpResponseRedirect('/user/groups/')

def test(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	pic = user.picture_set.all()[0]
	return render(request, 'user/test.html', 
		{
			'user': user,
			'picture': pic,
		})

django/Website/user/templates/user/change_user_picture.html
{% extends "home/base.html" %}

{% block content %}
<form id="change_user_picture_form" action="/user/cp{{ user_id }}/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<table>
		<tr>
			<td><label for="user_picture">Picture:</label></td>
			<td><input type="file" id="user_picture" class="" name="user_picture"></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn btn-primary" type="submit" value="Change picture"></td>
		</tr>
	</table>
</form>
{% endblock %}

django/Website/user/templates/user/create_group.html
{% extends "home/base.html" %}

{% block content %}
<div id="create_group_wrapper">
<form id="create_group_form" action="/user/cg/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<table id="create_group_table">
		<tr>
			<td><label for="group_name">Group name:</label></td>
			<td><input type="text" id="group_name" class="" name="group_name"></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn btn-primary" type="submit" value="Create group"></td>
		</tr>
	</table>
</form>
</div>
{% endblock %}

django/Website/user/templates/user/create_user.html
{% extends "home/base.html" %}

{% block content %}
<form id="login_button" action="{% url 'user:login' %}" method="post">
	{% csrf_token %}
	<input class="btn btn-primary" type="submit" value="Login">
</form>
<h2> OR </h2>
<form id="create_user_form" action="/user/cu/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<table id="create_user_table">
		<tr>
			<td><label for="name">Name:</label></td>
			<td><input type="text" id="name" name="name"></td>
		</tr>
		<tr>
			<td><label for="email">ASU Email:</label></td>
			<td><input type="email" id="email" name="email"></td>
		</tr>
		<tr>
			<td><label for="pwd">Password:</label></td>
			<td><input type="password" id="pwd" name="pwd"></td>
		</tr>
		<tr>
			<td><label for="pwd_check">Retype Password:</label></td>
			<td><input type="password" id="pwd_check" name="pwd_check"></td>
		</tr>
		<tr>
			<td><label for="grad_year">Grad Year:</label></td>
			<td><input type="text" id="grad_year" name="grad_year"></td>
		</tr>
		<tr>
			<td><label for="user_picture">Picture:</label></td>
			<td><input type="file" id="user_picture" class="" name="user_picture"></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn btn-primary" type="submit" value="Create user"></td>
		</tr>
	</table>
</form>
{% endblock %}

django/Website/user/templates/user/group.html
{% extends "home/base.html" %}

{% block content %}
<div id="group_index">
<table>
	<tr>
	<td>
		<h2>{{ group.name }} Members </h2>
		<ul>
		{% for member in group_members %}
			<li><a href="{% url 'user:user' member.id %}">
				<img src="{{ member.user_picture.url }}">{{ member.name }}
			</a></li>
		{% endfor %}
		</ul>
	</td>
	<td>
		{% if not user_in_group %}
		<form id="join_group" action="{% url 'user:join_group' group.id %}" method="post">
		{% csrf_token %}
		<input class="btn btn-primary" type="submit" value="Join Group">
		</form>
		{% else %}
		<form id="leave_group" action="{% url 'user:leave_group' group.id %}" method="post">
		{% csrf_token %}
		<input class="btn btn-danger" type="submit" value="Leave Group">
		</form>
		{% endif %}
	</td>
	</tr>
</table>
</div>
{% endblock %}

django/Website/user/templates/user/group_index.html
{% extends "home/base.html" %}

{% block content %}
<table id="group_index">
<tr>
	<td id="group_list">
		<ul>
		{% for group in groups %}
			<li><a href="{% url 'user:group' group.id %}">{{ group.name }}</a></li>
		{% endfor %}
		</ul>
	</td>
	<td id="create_group_button">
		<form id="create_group" action="{% url 'user:create_group' %}" method="post">
		{% csrf_token %}
		<input class="btn btn-primary" type="submit" value="Create Group">
		</form>
	</td>
</tr>
</table>

{% endblock %}

django/Website/user/templates/user/index.html
{% extends "home/base.html" %}

django/Website/user/templates/user/login.html
{% extends "home/base.html" %}

{% block content %}
<form id="login_form" action="/user/li/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<table id="create_user_table">
		<tr>
			<td><label for="email">Email:</label></td>
			<td><input type="text" id="email" name="email"></td>
		</tr>
		<tr>
			<td><label for="pwd">Password:</label></td>
			<td><input type="password" id="pwd" name="pwd"></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn btn-primary" type="submit" value="Login"></td>
		</tr>
	</table>
</form>
{% endblock %}

django/Website/user/templates/user/login_button.html
<form id="login_button" action="{% url 'user:login' %}" method="post">
	{% csrf_token %}
	<input class="btn btn-primary" type="submit" value="Login">
</form>

django/Website/user/templates/user/test.html
{% extends "home/base.html" %}

{% block content %}
<h1>{{ user.name }}</h1>
<h3>{{ user.email }}</h3>
<h3>{{ user.grad_year }}</h3>
<img src='{{ picture.pic }}'>
{% endblock %}

django/Website/user/templates/user/user.html
{% extends "home/base.html" %}

{% block content %}
<style>

.user_page_leaderboard {
	width: 100%;
}

.user_page_leaderboard thead {
	font-size: large;
}

.user_page_leaderboard tbody tr:nth-child(even) {
	background-color: #f2f2f2;
}

.user_page_leaderboard tbody tr:hover {
	background-color: #d0d891;
}

.user_page_leaderboard th {
	text-align: left;
	padding: 10px;
	border-bottom: 1px solid;
	background-color: #9bff8a;
}

.user_page_leaderboard td {
	text-align: left;
	padding: 10px;
	font-size:20px;
}

</style>

<div id="user_page">
	<table id="user_page_table">
	<tr>
	<td>
		<div id="user_picture">
		<img src='{{ user.user_picture.url }}'>
		{% if current_user %}
		<form id="change_picture" method="post"  action="/user/changepicture{{ user.id }}/">
		{% csrf_token %}
			<input class="btn btn-primary" type="submit" value="Change Picture">
		</form>
		{% endif %}
	</div>
	</td>
	<td id="user_info">
		<h1>{{ user.name }}</h1>
		<h3>{{ user.email }}</h3>
		<h3>{{ user.grad_year }}</h3>
	</td>
	</tr>
	<tr>
		<table class="user_page_leaderboard">
		<thead>
		<tr>
			<th>Challenge</th>
			<th>Error Rate</th>
			<th>Group</th>
			<th>Date Submitted</th>
		</tr>
		</thead>
		<tbody>
			{% for submission in submissions %}
			<tr>
				<td><a href="{% url 'challenge:challenge' submission.challenge.id %}">{{ submission.challenge.challenge_name }}</a></td>
				<td>{{ submission.error_rate }}</td>
				<td><a href="{% url 'user:group' submission.group.id %}">{{ submission.group.name }}</a></td>
				<td>{{ submission.latest_submission }}</td>
			</tr>
			{% endfor%}
		</tbody>
		</table>
	</tr>
	</table>
</div>
{% endblock %}

django/Website/user/templates/user/user_index.html
{% extends "home/base.html" %}

{% block content %}
<div id="user_list">
<ul>
{% for user in all_users %}
	<li><a href="{% url 'user:user' user.id %}">{{ user.name }}</a></li>
{% endfor %}
</ul>
</div>
{% endblock %}