django/Website/Website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^challenge/', include('challenge.urls')),
    url(r'^admin/', admin.site.urls)
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/Website/challenge/urls.py
from django.conf.urls import url
from . import views

app_name = 'challenge'
urlpatterns = [
	# url(r'^$', views.UserView.as_view(), name='index'),
	url(r'^$', views.challenges_home, name='home'),
	url(r'^(?P<challenge_id>[0-9]+)/$', views.challenge_page, name='challenge'),
	url(r'^(?P<challenge_id>[0-9]+)/helpcomment/$', views.help_comment, name='base_help_comment'),
	url(r'^(?P<challenge_id>[0-9]+)/helpcomment/(((?P<comment_id>[0-9]+)/)*)$', views.help_comment, name='help_comment'),
	url(r'^(?P<challenge_id>[0-9]+)/submit/$', views.submit, name='submit'),
	url(r'^submit/$', views.process_submit, name='process_submit'),
	url(r'^helpcomment/(?P<comment_id>[0-9]+)/$', views.index_help_comment, name="comment"),
	url(r'^post_comment/$', views.process_help_comment, name='process_help_comment'),
	# url(r'^test(?P<challenge_id>[0-9]+)/$', views.test, name='test')
]

django/Website/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^about/$', views.about, name='about'),
]

django/Website/user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
	url(r'^user_index/$', views.user_index, name='all_users'),
	url(r'^(?P<user_id>[0-9]+)/$', views.user, name='user'),
	url(r'^login/$', views.login, name='login'),
	url(r'^li/$', views.process_login, name='process_login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^create_user/$', views.create_user, name='create_user'),
	url(r'^cu/$', views.process_new_user, name='process_new_user'),
	url(r'^changepicture(?P<user_id>[0-9]+)/$', views.change_user_picture, name='change_user_picture'),
	url(r'^cp(?P<user_id>[0-9]+)/$', views.process_change_user_picture, name='process_change_user_picture'),
	url(r'^group(?P<group_id>[0-9]+)/$', views.group, name='group'),
	url(r'^groups/$', views.group_index, name='group_index'),
	url(r'^create_group/$', views.create_group, name='create_group'),
	url(r'^cg/$', views.process_new_group, name='process_new_group'),
	url(r'^join_group(?P<group_id>[0-9]+)/$', views.join_group, name='join_group'),
	url(r'^leave_group(?P<group_id>[0-9]+)/$', views.leave_group, name='leave_group'),
]

django/Website/challenge/models.py
import os

from django.db import models
from django.db.models.signals import post_save, post_delete, pre_delete
from django.conf import settings
from django.core.files.storage import FileSystemStorage as FSS
from Website.python import tools

class Challenge(models.Model):
	challenge_name = models.CharField(max_length=100)
	challenge_description = models.TextField()
	challenge_files = models.FileField(upload_to="challenges\\", max_length=300, default='\\challenges\\default.zip')
	date_created = models.DateTimeField('date_created')
	challenge_image = models.ImageField(upload_to="challenges\\challenge_avis\\", max_length=300, default='\\challenges\\challenge_avis\\default.jpg')
	test_key = models.TextField(blank=True, null=True)
	submission_count = models.IntegerField(default=0)

	# If a teacher wants to use the website to create a challenge,
	# give them the power to require students upload their code for the challenge too
	code_required = models.BooleanField(default=False)

	def save(self):
		super(Challenge, self).save()

		if self.challenge_files.name == None:
			return

		zip_filepath = settings.MEDIA_ROOT + self.challenge_files.name
		(valid_challenge_files, test_key) = tools.validate_challenge_files(zip_filepath)
		if valid_challenge_files:
			self.test_key = test_key
			super(Challenge, self).save()
		else:
			os.remove(zip_filepath)
			self.delete()
			raise Exception("Challenge files invalid")

	# returns a list of the "num_challenges_requested" most recent Challenge objects
	def get_latest_challenges(num_challenges_requested):
		return Challenge.objects.order_by('date_created')[:num_challenges_requested]
	
	# returns a list of the "num_challenges_requested" most popular Challenge objects (by submission count)
	def get_popular_challenges(num_challenges_requested):
		return Challenge.objects.order_by('submission_count')[:num_challenges_requested]

	def __str__(self):
		return self.challenge_name

def challenge_pre_delete(sender, instance, **kwargs):
	instance.challenge_files.delete()

	if not instance.challenge_image.name.split("\\")[-1] == "default.jpg":
		instance.challenge_image.delete()

pre_delete.connect(challenge_pre_delete, sender=Challenge)

class Submission(models.Model):
	challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, default=1)
	group = models.ForeignKey('user.Group', on_delete=models.CASCADE, default=1)
	user = models.ForeignKey('user.User', null=True, on_delete=models.SET_NULL)
	error_rate = models.DecimalField(max_digits=4, decimal_places=3)
	latest_submission = models.DateTimeField('latest_submission')
	code_files = models.FileField(upload_to="groups\\", max_length=300, blank=True, null=True)


	def __str__(self):
		d = str(self.latest_submission).split()
		d = d[0] + "_" + d[1].split("+")[0]
		return  self.challenge.challenge_name + "_" + self.group.name + "_" + d

def submission_post_save(sender, instance, **kwargs):

	# Increment the submission count of the challenge submitted to 
	challenge_submitted_to = instance.challenge
	challenge_submitted_to.submission_count += 1
	challenge_submitted_to.save()
post_save.connect(submission_post_save, sender=Submission)

def submission_pre_delete(sender, instance, **kwargs):
	# Decrement the submission count of the challenge that was submitted to
	challenge_submitted_to = instance.challenge
	challenge_submitted_to.submission_count -= 1
	challenge_submitted_to.save()
pre_delete.connect(submission_pre_delete, sender=Submission)

class HelpComment(models.Model):
	challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, default=1)
	user = models.ForeignKey('user.User', on_delete=models.CASCADE, default=1)
	comment_replied_to = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
	comment_text = models.TextField()
	date = models.DateTimeField('date written')
	num_replies = models.IntegerField(default=0)
	up_votes = models.IntegerField(default=0)
	down_votes = models.IntegerField(default=0)
	pictures = models.ManyToManyField('home.Picture')

	def __str__(self):
		d = str(self.date).split()
		d = d[0] + "_" + d[1].split("+")[0]
		return self.user.name + "_" + d

django/Website/challenge/forms.py
from django import forms

class CommentForm(forms.Form):
	comment_text = forms.CharField(label='comment_text', max_length=5000)
	challenge_id = forms.IntegerField(label='challenge_id')
	comment_id = forms.IntegerField(label='comment_id')

class SubmissionForm(forms.Form):
	challenge_id = forms.IntegerField(label='challenge_id')
	user_id = forms.IntegerField(label='user_id')
	group = forms.CharField(label='group', max_length=100)
	code_files = forms.FileField(label='code_files', required=False)
	submission_file = forms.FileField(label='submission_file')

django/Website/challenge/views.py
from django.shortcuts import render, get_object_or_404
from Website.python import tools
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from .models import Challenge, Submission, HelpComment
from user.models import User, Group
from .forms import CommentForm, SubmissionForm

import datetime

def challenges_home(request):
	latest_challenge_list = Challenge.get_latest_challenges(5)
	popular_challenge_list = Challenge.get_popular_challenges(5)
	all_challenges = Challenge.objects.order_by('challenge_name')
	return render(request, 'challenge/index.html', {
			'latest_challenge_list': latest_challenge_list,
			'popular_challenge_list': popular_challenge_list,
			'all_challenges': all_challenges,
		})

def challenge_page(request, challenge_id):
	challenge = get_object_or_404(Challenge, pk=challenge_id)
	latest_comment_list = HelpComment.objects.filter(comment_replied_to=None).filter(challenge=challenge).order_by('date')
	submissions = Submission.objects.filter(challenge=challenge).order_by('-error_rate')[:100]

	return render(request, 'challenge/challenge.html', 
		{
			'challenge': challenge,
			'latest_comment_list': latest_comment_list,
			'submissions': submissions,
			'media_path': settings.MEDIA_ROOT,
		})

def submit(request, challenge_id):
	challenge = get_object_or_404(Challenge, pk=challenge_id)
	groups = tools.get_session_groups(request.session)

	if groups:
		return render(request, 'challenge/submit.html', {
				"challenge": challenge,
				"groups": groups,
			})
	else:
		return HttpResponseRedirect('/user/login/')

def process_submit(request):
	if request.method == 'POST':
		form = SubmissionForm(request.POST, request.FILES)
		if form.is_valid():
			challenge = Challenge.objects.get(id=form.cleaned_data['challenge_id'])
			group = Group.objects.get(name=form.cleaned_data['group'])
			user = User.objects.get(id=form.cleaned_data['user_id'])
			submission_file = form.cleaned_data['submission_file']

			if tools.submission_is_valid(submission_file):
				test_key = challenge.test_key
				error_rate = tools.evaluate_submission(submission_file, test_key)
			else:
				return HttpResponseRedirect('/challenge/' + challenge.id + '/submit')

			if form.cleaned_data['code_files'] == None:
				submission = Submission(challenge=challenge, group=group, user=user, error_rate=error_rate, latest_submission=tools.datetimenow())
			else:
				submission = Submission(challenge=challenge, group=group, user=user, error_rate=error_rate,\
										latest_submission=tools.datetimenow(), code_files=form.cleaned_data['code_files'])

			submission.save()
			return render(request, 'challenge/submission_results.html', {
					'challenge': challenge,
					'error_rate': error_rate,
				})
		else:
			return HttpResponse("Form is invalid")
	else:
		return HttpResponse("Invalid request")

def index_help_comment(request, comment_id):
	comment = get_object_or_404(HelpComment, pk=comment_id)
	sub_comments = HelpComment.objects.filter(comment_replied_to=comment).order_by('date')
	return render(request, 'challenge/comment_index.html', {
			'comment': comment,
			'sub_comments': sub_comments,
		})

def help_comment(request, challenge_id, comment_id=0):
	challenge = get_object_or_404(Challenge, pk=challenge_id)

	try:
		comment_replied_to = HelpComment.objects.get(id=comment_id)
	except HelpComment.DoesNotExist:
		comment_replied_to = None

	return render(request, 'challenge/help_comment.html', 
		{
			'challenge': challenge,
			'comment_replied_to': comment_replied_to,
		})

def process_help_comment(request):
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment_text = form.cleaned_data['comment_text']
			challenge = Challenge.objects.get(id=form.cleaned_data['challenge_id'])
			user = User.objects.get(id=request.session['user_id'])
			date = tools.datetimenow()

			# If the comment being processed is a reply to another comment
			if (form.cleaned_data['comment_id'] == 0):
				help_comment = HelpComment(challenge=challenge, user=user, comment_text=comment_text, date=date)
			else:
				comment = HelpComment.objects.get(pk=form.cleaned_data['comment_id'])
				help_comment = HelpComment(challenge=challenge, user=user, comment_replied_to=comment, comment_text=comment_text, date=date)
				comment.num_replies += 1
				comment.save()
			help_comment.save()

			return HttpResponseRedirect('/challenge/' + str(challenge.id) + '/')
		else:
			return HttpResponse("Form is not valid")

	else:
		pass
		# do something here

# def test(request, challenge_id):
# 	challenge = get_object_or_404(Challenge, pk=challenge_id)
# 	return render (request, 'challenge/test_download.html',
# 		{
# 			'challenge': challenge,
# 			'media_path': settings.MEDIA_ROOT,
# 		})

django/Website/challenge/templates/challenge/challenge.html
{% extends "home/base.html" %}

{% block content %}
<div id="challenge_page">
	<table>
	<tr>
		<td><img src='{{ challenge.challenge_image.url }}' id="challenge_image"></td>
	</tr>
	<tr>
		<td><h1>{{ challenge.challenge_name }}</h1></td>
	</tr>
	<tr>
		<td><p>{{ challenge.challenge_description }}</p></td>
	</tr>
	<tr></tr>
	<tr>
		<td align="center">
		<table id="challenge_action_buttons">
			<tr>
				<td><form action='{{ challenge.challenge_files.url }}'>
					<input type="submit" value="Dowload Challenge" />
				</form>
				</td>
				<td><form action="{% url 'challenge:submit' challenge.id %}">
					<input type="submit" value="Submit" />
				</form>
				</td>
			</tr>
		</table>
		</td>
	</tr>

	<tr id="challenge_page_row_break"></tr>

	<tr>
		{% include 'challenge/challenge_leaderboard.html' %}
	</tr>
	<tr><td><br></td></tr>
	<tr>
		<td><form action="{% url 'challenge:base_help_comment' challenge.id %}">
					<input type="submit" value="Post Comment" />
			</form>
		</td>
	</tr>
	<tr>
		<table id="help_comments">
			<tr>
				<td>
				{% for help_comment in latest_comment_list %}
					{% include 'challenge/comment_frame.html' %}
				{% endfor %}
				</td>
			</tr>
		</table>
	</tr>
	</table>
</div>
{% endblock %}

django/Website/challenge/templates/challenge/challenge_leaderboard.html
<table id="challenge{{challenge.id}}_leaderboard" class="index_challenge_leaderboard">
<thead>
	<tr>
		<th>Error Rate</th>
		<th>Group</th>
		<th>Date Submitted</th>
	</tr>
</thead>
<tbody>
	{% for submission in submissions %}
	<tr>
		<td>{{ submission.error_rate }}</td>
		<td><a href="{% url 'user:group' submission.group.id %}">{{ submission.group.name }}</a>
		</td>
		<td>{{ submission.latest_submission }}</td>
	</tr>
	{% endfor%}
</tbody>
</table>

django/Website/challenge/templates/challenge/comment_frame.html
<table id="comment">
	<tr id="posted_by">
		<td id="user_img">
			<img src="{{ help_comment.user.user_picture.url }}">
		</td>
		<td>
			<a href="{% url 'user:user' help_comment.user.id %}">
			<p>{{ help_comment.user.name }}</p>
			</a>
			<br>
			<p>{{ help_comment.date }}</p>
		</td>
	</tr>
	</a>
	<tr>
		<td colspan="2"><p id="comment_text">{{ help_comment.comment_text }}</p>
		</td>
	</tr>
	<tr id="reply_row">
		<td>
		<form id="reply_form" action="/challenge/{{ help_comment.challenge.id }}/helpcomment/{{ help_comment.id }}/" method="post">
		{% csrf_token %}
		<input type="submit" value="Reply">
		</form>
		</td>
		<td>
		{% if help_comment.num_replies > 0 %}
			<a href="{% url 'challenge:comment' help_comment.id %}">see replies</a>
		{% endif %}
		</td>
	</tr>
</table>

django/Website/challenge/templates/challenge/comment_index.html
{% extends "home/base.html" %}

{% block content %}
<a href="{% url 'challenge:challenge' comment.challenge.id %}">
	<h3>CHALLENGE: {{ comment.challenge.challenge_name }}</h3>
</a>
<table id="comment_index">
	<tr id="root_comment">
		{% with comment as help_comment %}
		<td>
			{% include 'challenge/comment_frame.html' %}
		</td>
		{% endwith %}
	</tr>

	{% for help_comment in sub_comments %}
	<tr>
		<td></td>
		<td>
		{% include 'challenge/comment_frame.html' %}
		</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

django/Website/challenge/templates/challenge/help_comment.html
{% extends "home/base.html" %}

{% block content %}
{% if not comment_replied_to == None %}
	{% with comment_replied_to as help_comment %}
		{% include 'challenge/comment_frame.html' %}
	{% endwith %}
{% endif %}

<br><br>

<form id="comment_form" action="/challenge/post_comment/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<table id="comment_form_table">
		<tr>
			<td><label for="comment_text">Comment</label></td>
		</tr>
		<tr id="comment_row">
			<td><input type="text" id="comment_text" name="comment_text"></td>
		</tr>
		<tr hidden>
			<td><label for="challenge_id"></label></td>
			<td><input type="number" value="{{ challenge.id }}" id="challenge_id" name="challenge_id"></td>
		</tr>
		<tr hidden>
			<td><label for="comment_id"></label></td>
			{% if not comment_replied_to == None %}
				<td><input type="number" value="{{ comment_replied_to.id }}" id="comment_id" name="comment_id"></td>
			{% else %}
				<td><input type="number" value="0" id="comment_id" name="comment_id"></td>
			{% endif %}
		</tr>
		<tr>
			<td><input class="btn btn-primary" type="submit" value="Post Comment"></td>
		</tr>
	</table>
</form>
{% endblock %}

django/Website/challenge/templates/challenge/index.html
{% extends "home/base.html" %}

{% block content %}
<div id="list_all_challenges">
	<h3>All Challenges</h3>
	<ul>
	{% for challenge in all_challenges %}
		<a href="{% url 'challenge:challenge' challenge.id %}">
			<li>{{ challenge.challenge_name }}</li>
		</a>
	{% endfor %}
	</ul>
</div>
{% endblock %}

django/Website/challenge/templates/challenge/submission_results.html
{% extends "home/base.html" %}

{% block content %}
<h3>Submission for: <a href="{% url 'challenge:challenge' challenge.id %}">{{ challenge.challenge_name }}</a></h3>
<h2>Error rate: {{ error_rate }}</h2>
{% endblock %}

django/Website/challenge/templates/challenge/submit.html
{% extends "home/base.html" %}

{% block content %}
<h3>Submitting for: <a href="{% url 'challenge:challenge' challenge.id %}">{{ challenge.challenge_name }}</a></h3>
<form id="submit_form" action="/challenge/submit/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<table id="submit_form">
		<tr>
			<td><label for="submission_file">Submission:</label></td>
			<td><input type="file" id="submission_file" class="" name="submission_file"></td>
		</tr>
		{% if challenge.code_required %}
		<tr>
			<td><label for="code_files">Code:</label></td>
			<td><input type="file" id="code_files" name="code_files"></td>
		</tr>
		{% endif %}
		<tr>
			<td><label for="group">Group:</label></td>
			{% for group in groups %}
			<td>
				<input type="radio" id="group" name="group" value="{{ group.name }}"> {{ group.name }}
			</td>
			{% endfor %}
		</tr>
		<tr hidden>
			<td><label for="challenge_id"></label></td>
			<td><input type="number" value="{{ challenge.id }}" id="challenge_id" class="" name="challenge_id"></td>
		</tr>
		<tr hidden>
			<td><label for="user_id"></label></td>
			<td><input type="number" value="{{ request.session.user_id }}" id="user_id" class="" name="user_id"></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn btn-primary" type="submit" value="Submit"></td>
		</tr>
	</table>
</form>
{% endblock %}