django/Website/Website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^challenge/', include('challenge.urls')),
    url(r'^admin/', admin.site.urls)
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/Website/challenge/urls.py
from django.conf.urls import url
from . import views

app_name = 'challenge'
urlpatterns = [
	# url(r'^$', views.UserView.as_view(), name='index'),
	url(r'^$', views.challenges_home, name='home'),
	url(r'^(?P<challenge_id>[0-9]+)/$', views.challenge_page, name='challenge'),
	url(r'^(?P<challenge_id>[0-9]+)/helpcomment/$', views.help_comment, name='base_help_comment'),
	url(r'^(?P<challenge_id>[0-9]+)/helpcomment/(((?P<comment_id>[0-9]+)/)*)$', views.help_comment, name='help_comment'),
	url(r'^(?P<challenge_id>[0-9]+)/submit/$', views.submit, name='submit'),
	url(r'^submit/$', views.process_submit, name='process_submit'),
	url(r'^helpcomment/(?P<comment_id>[0-9]+)/$', views.index_help_comment, name="comment"),
	url(r'^post_comment/$', views.process_help_comment, name='process_help_comment'),
	# url(r'^test(?P<challenge_id>[0-9]+)/$', views.test, name='test')
]

django/Website/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^about/$', views.about, name='about'),
]

django/Website/user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
	url(r'^user_index/$', views.user_index, name='all_users'),
	url(r'^(?P<user_id>[0-9]+)/$', views.user, name='user'),
	url(r'^login/$', views.login, name='login'),
	url(r'^li/$', views.process_login, name='process_login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^create_user/$', views.create_user, name='create_user'),
	url(r'^cu/$', views.process_new_user, name='process_new_user'),
	url(r'^changepicture(?P<user_id>[0-9]+)/$', views.change_user_picture, name='change_user_picture'),
	url(r'^cp(?P<user_id>[0-9]+)/$', views.process_change_user_picture, name='process_change_user_picture'),
	url(r'^group(?P<group_id>[0-9]+)/$', views.group, name='group'),
	url(r'^groups/$', views.group_index, name='group_index'),
	url(r'^create_group/$', views.create_group, name='create_group'),
	url(r'^cg/$', views.process_new_group, name='process_new_group'),
	url(r'^join_group(?P<group_id>[0-9]+)/$', views.join_group, name='join_group'),
	url(r'^leave_group(?P<group_id>[0-9]+)/$', views.leave_group, name='leave_group'),
]

django/Website/home/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage as FSS

ps = FSS(location=(settings.MEDIA_ROOT + '\\images\\test_images\\'))

class Picture(models.Model):
	u = models.ForeignKey('user.User', on_delete=models.CASCADE, default=1)
	pic = models.ImageField(storage=ps, max_length=300, default='\\images\\default.jpg')

django/Website/home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from challenge.models import Challenge

def home(request):
	return render(request, 'home/index.html', {})

def about(request):
	return HttpResponseRedirect('/static/text/file_format_guidelines.txt')

django/Website/home/templates/home/base.html
<!doctype html>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<html>
	<head>
		<div id="header">
			<div id="university_department_name">Appalachian State University Computer Science Department
			</div>
			<div id="header_box">
				<div id="block_header_text">
					<h1 id="page_name_header" class="text header_text">Machine Learning and Vision Coliseum</h1>
					{% block description %}{% endblock %}
				</div>
				<div id="navbar" class="navbar">
					<a href="{% url 'home:home' %}">HOME</a>
					<a href="{% url 'challenge:home' %}">CHALLENGES</a>
					<a href="{% url 'user:group_index' %}">GROUPS</a>
					<a href="{% url 'user:all_users' %}">USERS</a>
					<a href="{% url 'home:about' %}">ABOUT</a>
				</div>
				{% if request.session.user_id %}
				<div id="session_navbar" class="navbar">
					<a href="{% url 'user:user' request.session.user_id %}">PROFILE</a>
					<a href="{% url 'user:logout' %}">LOGOUT</a>
				</div>
				{% else %}
				<div id="login_navbar" class="navbar">
					<a href="{% url 'user:login' %}">LOGIN</a>
					<a href="{% url 'user:create_user' %}">CREATE USER</a>
				</div>
				{% endif %}
			</div>
		</div>
	</head>
	<body>
		{% block content %}{% endblock %}
	</body>
</html>

django/Website/home/templates/home/index.html
{% extends "./base.html" %}
{% block description %}
<p id="site_description" class="text header_text">Test your machine learning, algorithmic know-how on this competitive platform and see if you can best your fellow Mountaineers. Download the files for the problem you want to try and upload your results! Or create your own challenge problem!
</p>
{% endblock %}